name: "threebyfour"
description: "A new Flutter project."
publish_to: "none"
version: "1.0.0+1"
environment:
  sdk: "^3.7.2"
  flutter: "3.29.3"
dependencies:
  flutter:
    sdk: "flutter"
  cupertino_icons: "^1.0.8"
  go_router: "^16.0.0"
  shared_preferences: "^2.5.3"
  flutter_riverpod: "^2.6.1"
  permission_handler: "^12.0.1"
  file_picker: "^10.2.1"
  transparent_image: "^2.0.1"
  photo_view: "^0.15.0"
  flutter_staggered_grid_view: "^0.7.0"
  responsive_framework: "^1.5.1"
  animations: "^2.0.11"
  pausable_timer: "^3.1.0+3"
  intl: "^0.20.2"
  inno_build: "^0.3.0"
dev_dependencies:
  flutter_test:
    sdk: "flutter"
  flutter_lints: "^5.0.0"
  custom_lint: "^0.7.6"
  riverpod_lint: "^2.6.5"
  inno_bundle: ^0.9.0
flutter:
  uses-material-design: true
  fonts:
    - family: "Staatliches"
      fonts:
        - asset: "assets/fonts/Staatliches-Regular.ttf"
    - family: "Inter"
      fonts:
inno_bundle:
  id: c62c352a-ca48-50a1-9b0e-e5a4eadbd3bf
  publisher: boredcodebyk
  name: threebyfour