name: "Build"

on:
    push

jobs:
    build:
        name: "Build"
        runs-on: "windows-latest"
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set Up Java
            uses: actions/setup-java@v3.12.0
            with:
                distribution: 'adopt'
                java-version: '21'
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version-file: pubspec.yaml # path to pubspec.yaml
          - run: flutter --version
          - name: "Build APK"
            run: flutter build apk --release
          - name: "Build Windows"  
            run: flutter build windows --release
          - name: Archive Release
            uses: thedoctor0/zip-release@master
            with:
                type: 'zip'
                filename: threebyfour-${{github.ref_name}}-windows.zip
                directory: build/windows/x64/runner/Release
          - name: Upload Artifacts
            uses: actions/upload-artifact@v4
            with:
                name: Releases
                path: |
                    build/app/outputs/flutter-apk/app-release.apk
                    build/windows/runner/x64/runner/Release/threebyfour-${{github.ref_name}}-windows.zip
                

