name: "Build and Release"

on:
  push:
    tags:
      - 'v*'

jobs:
    build_windows:
      name: "Windows Build"
      runs-on: "windows-latest"
      steps:
        - name: Clone repository
          uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version-file: pubspec.yaml # path to pubspec.yaml
        - name: "Build Windows"  
          run: dart run inno_bundle:build --release
        - name: Archive Release
          run: Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath threebyfour-${{github.ref_name}}-windows.zip
        - name: Copy and Rename Installer
          run: |
            Copy-Item build/windows/x64/installer/Release/Threebyfour-x86_64-1.0.0+1-Installer.exe Threebyfour-x86_64-1.0.0+1-Installer.exe
            Rename-Item Threebyfour-x86_64-1.0.0+1-Installer.exe threebyfour-x86_64-${{github.ref_name}}-Installer.exe
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
              name: Windows-Build
              path: threebyfour-x86_64-${{github.ref_name}}-Installer.exe
    build_apk:
        name: "APK Build"
        runs-on: "ubuntu-latest"
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        steps:
          - name: Clone repository
            uses: actions/checkout@v4
          - name: Set Up Java
            uses: actions/setup-java@v3.12.0
            with:
                distribution: 'adopt'
                java-version: '21'
          - name: Set up Flutter
            uses: subosito/flutter-action@v2
            with:
              channel: stable
              flutter-version-file: pubspec.yaml # path to pubspec.yaml
          - run: flutter --version
          - name: Decode Keystore
            run: |
              echo $KEYSTORE_BASE64 | base64 --decode > android/app/keystore.jks
          - name: Create key.properties
            run: |
              echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
              echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
              echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
              echo "storeFile=keystore.jks" >> android/key.properties
          - name: "Build APK"
            run: flutter build apk --release
          - name: Copy and Rename Installer
            run: |    
              cp build/app/outputs/flutter-apk/app-release.apk app-release.apk
              mv app-release.apk threebyfour-${{github.ref_name}}.apk
          - name: Upload Artifacts
            uses: actions/upload-artifact@v4
            with:
                name: Android-Build
                path: threebyfour-${{github.ref_name}}.apk
                
    release:
      permissions:
        contents: write
      needs: 
        - build_apk
        - build_windows
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Download APK
          uses: actions/download-artifact@v4
          with:
            name: Android-Build
            path: threebyfour-${{github.ref_name}}.apk
        - name: Download Windows Installer
          uses: actions/download-artifact@v4
          with:
            name: Windows-Build
            path: threebyfour-x86_64-${{github.ref_name}}-Installer.exe
        - name: Release
          uses: softprops/action-gh-release@v2
          if: github.ref_type == 'tag'
          with:
            body_path: WHATSNEW.md
            files: |
              threebyfour-x86_64-${{github.ref_name}}-Installer.exe
              threebyfour-${{github.ref_name}}.apk